<?php
$server_name="localhost";
$username="root";
$password="";
$database_name="student_database1";
 
$conn=mysqli_connect($server_name,$username,$password,$database_name);
//now check the connection
if(!$conn)
{
	die("Connection Failed:" . mysqli_connect_error());
}
if(isset($_POST['save1']))
{	
	 $FIRST_NAME = $_POST['fname'];
	 $SECOND_NAME = $_POST['sname'];
	 $GENDER=$_POST['gen'];
	 $DOB = $_POST['dob'];
	 $EMAIL = $_POST['mail'];
	 $FIRST_GRADUATE = $_POST['grad'];
	 $BLOOD_GROUP=$_POST['BG'];
	 $EMIS_NUMBER=$_POST['emis'];
	 $STUDENT_PHNO=$_POST['sph'];
	 $PERMANENT_ADDRESS=$_POST['pa'];
	 $COMMUNICATION_ADDRESS=$_POST['ca'];
	 $RELIGION=$_POST['grad'];
	 $COMMUNITY=$_POST['cas'];
	 $CASTE=$_POST['caste'];
	 $NATIONALITY=$_POST['nat'];
	 $STATE=$_POST['sta'];
	 $AADHAR_NUMBER=$_POST['ad'];
	 $ALLOTMENT_NUMBER=$_POST['allot'];
	 $ADMISSION_MODE=$_POST['am'];
	 $LATERAL_ENTRY=$_POST['la'];
	 $DATE_OF_ADMISSION=$_POST['doa'];
	 $COUNSELLING_NUMBER=$_POST['cn'];
	 $HOSTEL_TYPE=$_POST['ht'];
	 $HOSTELLER=$_POST['hos'];
	 $CERTIFICATE_ARE_SUBMITED=$_POST['ceas'];
	 $BANK_USER_NAME=$_POST['buname'];
	 $BANK_NAME=$_POST['bname'];
	 $BRANCH_NAME=$_POST['brname'];
	 $ACCOUNT_NUMBER=$_POST['an'];
	 $IFSC_CODE=$_POST['code'];
	 $FATHER_NAME=$_POST['Faname'];
	 $F_WORKING_SECTOR=$_POST['worksf'];
	 $FATHER_OCCUPATION=$_POST['faocu'];
	 $FATHER_PHNO=$_POST['fph'];
	 $MOTHER_NAME=$_POST['maname'];
	 $M_WORKING_SECTOR=$_POST['worksm'];
	 $MOTHER_OCCUPATION=$_POST['maocu'];
	 $MOTHER_PHNO=$_POST['mph'];
	 $ORPHAN=$_POST['orp'];
	 $GUARDIAN_NAME=$_POST['guname'];
	 $ANNUAL_INCOME=$_POST['ain'];
	 $TENth_MARK=$_POST['10'];
	 $TEWELth_MARK=$_POST['12'];
	 $TAMIL_MARK=$_POST['t12'];
	 $ENGLISH_MARK=$_POST['e12'];
	 $MATHS_MARK=$_POST['m12'];
	 $BIOLOGY_COMPUTER_SCIENCE_MARK=$_POST['cob12'];
	 $CHEMISTRY=$_POST['c12'];
	 $PHYSICS=$_POST['P12'];
	 $CUT_OFF_MARK=$_POST['com'];
	 $sql_query = "INSERT INTO students_details (FIRST_NAME,SECOND_NAME,GENDER,DOB,EMAIL,FIRST_GRADUATE,BLOOD_GROUP,EMIS_NUMBER,STUDENT_PHNO,PERMANENT_ADDRESS,COMMUNICATION_ADDRESS,RELIGION,COMMUNITY,CASTE,NATIONALITY,STATE,AADHAR_NUMBER,ALLOTMENT_NUMBER,ADMISSION_MODE,LATERAL_ENTRY,DATE_OF_ADMISSION,COUNSELLING_NUMBER,HOSTEL_TYPE,HOSTELLER,CERTIFICATE_ARE_SUBMITED,BANK_USER_NAME,BANK_NAME,BRANCH_NAME,ACCOUNT_NUMBER,IFSC_CODE,FATHER_NAME,F_WORKING_SECTOR,FATHER_OCCUPATION,FATHER_PHNO,MOTHER_NAME,M_WORKING_SECTOR,MOTHER_OCCUPATION,MOTHER_PHNO,ORPHAN,GUARDIAN_NAME,ANNUAL_INCOME,TENth_MARK,TEWELth_MARK,TAMIL_MARK,ENGLISH_MARK,MATHS_MARK,BIOLOGY_COMPUTER_SCIENCE_MARK,CHEMISTRY,PHYSICS,CUT_OFF_MARK) 
	 VALUES ('$FIRST_NAME','$SECOND_NAME','$GENDER','$DOB','$EMAIL','$FIRST_GRADUATE','$BLOOD_GROUP','$EMIS_NUMBER','$STUDENT_PHNO','$PERMANENT_ADDRESS','$COMMUNICATION_ADDRESS','$RELIGION','$COMMUNITY','$CASTE','$NATIONALITY','$STATE','$AADHAR_NUMBER','$ALLOTMENT_NUMBER','$ADMISSION_MODE','$LATERAL_ENTRY','$DATE_OF_ADMISSION','$COUNSELLING_NUMBER','$HOSTEL_TYPE','$HOSTELLER','$CERTIFICATE_ARE_SUBMITED','$BANK_USER_NAME','$BANK_NAME','$BANK_NAME','$ACCOUNT_NUMBER','$IFSC_CODE','$FATHER_NAME','$F_WORKING_SECTOR','$FATHER_OCCUPATION','$FATHER_PHNO','$MOTHER_NAME','$M_WORKING_SECTOR','$MOTHER_OCCUPATION','$MOTHER_PHNO','$ORPHAN','$GUARDIAN_NAME','$ANNUAL_INCOME','$TENth_MARK','$TEWELth_MARK','$TAMIL_MARK','$ENGLISH_MARK','$MATHS_MARK','$BIOLOGY_COMPUTER_SCIENCE_MARK','$CHEMISTRY','$PHYSICS','$CUT_OFF_MARK')";
	 if (mysqli_query($conn, $sql_query)) 
	 {
		echo "New Details Entry inserted successfully !";
	 } 
	 else
     {
		echo "Error: " . $sql . "" . mysqli_error($conn);
	 }
	 mysqli_close($conn);
}
?>